from pathlib import Path
import argparse
import random


SHAPES = [
    (5120, 5120),
    # (7168, 7168),
    # (7168, 28672),
]

DENSITIES = [0.60, 0.35]


def format_density_tag(density: float) -> str:
    return str(int(round(density * 100)))


def generate_coordinate_set(rows: int, cols: int, nnz: int, rng: random.Random):
    total = rows * cols
    if nnz > total:
        raise ValueError(f"nnz={nnz} exceeds total elements={total}")

    positions = rng.sample(range(total), nnz)
    positions.sort()
    return positions


def write_matrix_market(path: Path, rows: int, cols: int, density: float, seed: int):
    rng = random.Random(seed)
    nnz = int(round(rows * cols * density))
    positions = generate_coordinate_set(rows, cols, nnz, rng)

    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        f.write("%%MatrixMarket matrix coordinate real general\n")
        f.write(f"% generated by generate_mtx.py with density={density:.2f}, seed={seed}\n")
        f.write(f"{rows} {cols} {nnz}\n")

        for pos in positions:
            row = pos // cols
            col = pos % cols
            value = rng.uniform(-1.0, 1.0)
            while value == 0.0:
                value = rng.uniform(-1.0, 1.0)
            # Matrix Market uses 1-based indices.
            f.write(f"{row + 1} {col + 1} {value:.8f}\n")


def main():
    parser = argparse.ArgumentParser(description="Generate Matrix Market test matrices for DASP benchmarking.")
    parser.add_argument(
        "--output-dir",
        default=str(Path(__file__).with_name("test") / "matrices"),
        help="Directory to write .mtx files into.",
    )
    parser.add_argument(
        "--base-seed",
        type=int,
        default=47,
        help="Base RNG seed. Each matrix gets a deterministic derived seed.",
    )
    args = parser.parse_args()

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    generated = []
    for shape_idx, (rows, cols) in enumerate(SHAPES):
        for density_idx, density in enumerate(DENSITIES):
            density_tag = format_density_tag(density)
            seed = args.base_seed + shape_idx * 100 + density_idx
            out_path = output_dir / f"{rows}x{cols}_d{density_tag}.mtx"
            write_matrix_market(out_path, rows, cols, density, seed)
            generated.append(out_path)
            print(f"Wrote {out_path}")

    print(f"Generated {len(generated)} matrices in {output_dir}")


if __name__ == "__main__":
    main()
